package news.bombomemail.article.event;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.transaction.TestTransaction;
import org.springframework.transaction.annotation.Transactional;

@SpringBootTest
@ActiveProfiles("test")
class ArticleArrivedEventPersistenceTest {

    @Autowired
    private ApplicationEventPublisher eventPublisher;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS recent_article (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    article_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    contents CLOB NOT NULL,
                    contents_text CLOB NOT NULL,
                    thumbnail_url VARCHAR(512),
                    expected_read_time TINYINT,
                    contents_summary VARCHAR(255) NOT NULL,
                    is_read BOOLEAN DEFAULT FALSE,
                    member_id BIGINT NOT NULL,
                    newsletter_id BIGINT NOT NULL,
                    arrived_date_time TIMESTAMP NOT NULL,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbcTemplate.update("DELETE FROM recent_article");
    }

    @Test
    @Transactional
    void 매일메일_도착_이벤트는_recent_article을_저장하지_않는다() {
        // when
        eventPublisher.publishEvent(ArticleArrivedEvent.of(
                1L,
                "매일메일",
                10L,
                "매일메일 발행 제목",
                2L,
                null,
                ArticleSource.MAEIL_MAIL_ISSUED
        ));
        TestTransaction.flagForCommit();
        TestTransaction.end();

        // then
        Integer recentArticleCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM recent_article",
                Integer.class
        );
        assertThat(recentArticleCount).isZero();
    }
}
