export const WEBVIEW_MESSAGES = {
  WEB_TO_RN: {
    SHOW_LOGIN_SCREEN: 'SHOW_LOGIN_SCREEN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
  },
  RN_TO_WEB: {
    GOOGLE_LOGIN_TOKEN: 'GOOGLE_LOGIN_TOKEN',
    APPLE_LOGIN_TOKEN: 'APPLE_LOGIN_TOKEN',
  },
} as const;