export const DEFAULT_SPEED = 4000;
export const INFINITY_START_SLIDE_INDEX = 1;
export const FINITE_START_SLIDE_INDEX = 0;
export const SWIPE_OFFSET_THRESHOLD = 50;
export const SWIPE_ANGLE_THRESHOLD = 30;
