// WebView message type constants

export const WEB_TO_RN_MESSAGE_TYPES = {
  SHOW_LOGIN_SCREEN: 'SHOW_LOGIN_SCREEN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  OPEN_BROWSER: 'OPEN_BROWSER',
} as const;

export const RN_TO_WEB_MESSAGE_TYPES = {
  GOOGLE_LOGIN_TOKEN: 'GOOGLE_LOGIN_TOKEN',
  APPLE_LOGIN_TOKEN: 'APPLE_LOGIN_TOKEN',
} as const;
