ALTER TABLE badge
    ADD COLUMN streak_day_count INT NULL;

UPDATE badge
SET streak_day_count = CASE streak_badge_tier
    WHEN 'SEVEN' THEN 7
    WHEN 'FIFTEEN' THEN 15
    WHEN 'THIRTY' THEN 30
    WHEN 'FIFTY' THEN 50
    WHEN 'HUNDRED' THEN 100
    WHEN 'TWO_HUNDRED' THEN 200
    WHEN 'THREE_HUNDRED' THEN 300
    WHEN 'FOUR_HUNDRED' THEN 400
    WHEN 'FIVE_HUNDRED' THEN 500
    ELSE NULL
END
WHERE badge_category = 'STREAK';
