name: 'Chromatic Deployment'
defaults:
  run:
    working-directory: ./frontend

on: push

jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm install
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
