name: pull requset - dev

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - server-dev

jobs:
  dev-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/bom-bom-server
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK v21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_DEV_PROPERTIES }}" > src/main/resources/application.yml
          mkdir -p src/test/resources
          echo "${{ secrets.APPLICATION_TEST_PROPERTIES }}" > src/test/resources/application-test.yml

      - name: 빌드하기 및 테스트 하기
        run: ./gradlew clean build
          
