name: CI
defaults:
  run:
    working-directory: ./frontend/web
on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - client
      - client-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      # - name: Setup Node.js
      #   uses: actions/setup-node@v5
      #   with:
      #     node-version: "22"
      #     cache: "pnpm"
      #     cache-dependency-path: "./frontend/web/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm run build

      # TODO : Deploy
