name: Backend Prod Server CI/CD  # ✅ dev → prod 이름 변경

on:
  push:
    branches:
      - server-sub   
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/bom-bom-server

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: application.yml 생성 (Prod 환경)
        shell: bash
        run: |
          mkdir -p src/main/resources src/test/resources
          printf '%s' "${{ secrets.APPLICATION_PROD_PROPERTIES }}" > src/main/resources/application.yml
          printf '%s' "${{ secrets.APPLICATION_TEST_PROPERTIES }}" > src/test/resources/application.yml

      - name: 빌드 및 테스트
        shell: bash
        env:
          SPRING_PROFILES_ACTIVE: test
          APPLE_P8_ESCAPED: ${{ secrets.APPLE_P8_ESCAPED }}
        run: |
          export OAUTH2_APPLE_PRIVATE_KEY="$(printf '%b' "${APPLE_P8_ESCAPED:?APPLE_P8_ESCAPED 시크릿이 없습니다}")"
          ./gradlew clean build --no-daemon

      - name: 테스트 리포트 업로드
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-and-html-reports
          path: |
            build/reports/tests/test
            build/test-results/test

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          if ! docker buildx inspect ci-builder &>/dev/null; then
            docker buildx create --use --name ci-builder
          else
            docker buildx use ci-builder
          fi
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/bom-bom:buildcache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/bom-bom:buildcache,mode=max \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/bom-bom:prod \
            --push .

  deploy:
    name: Production Server 배포
    needs: build
    runs-on: [ self-hosted, prod-sub ]  # ✅ main → prod (runner에 따라 조정)
    defaults:
      run:
        working-directory: ./backend/bom-bom-server

    environment:
      name: production
      url: https://api.bombom.news # ✅ 실제 운영 서비스 URL

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: .env file 생성
        run: |
          cat <<EOF > .env
          RDS_ENDPOINT=${{ secrets.PROD_RDS_ENDPOINT }}
          DATABASE=${{ secrets.PROD_DATABASE }}
          MYSQL_USER=${{ secrets.PROD_MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.PROD_MYSQL_PASSWORD }}
          SPRING_PROFILES_ACTIVE=prod
          PROD_OTEL_ENDPOINT=${{ secrets.PROD_OTEL_ENDPOINT }}
          EOF

      - name: 컨테이너 재실행 (p8 ENV 주입)
        shell: bash
        env:
          APPLE_P8_ESCAPED: ${{ secrets.PROD_APPLE_P8_ESCAPED }}
        run: |
          set -euo pipefail
          export OAUTH2_APPLE_PRIVATE_KEY="$(printf '%b' "$APPLE_P8_ESCAPED")"
          OAUTH2_APPLE_PRIVATE_KEY="$OAUTH2_APPLE_PRIVATE_KEY" \
          sudo docker compose \
            -f docker-compose-prod-sub.yml \
            --env-file .env \
            up -d --remove-orphans --pull=always
              
      - name: Docker 리소스 정리
        run: |
          sudo docker container prune -f --filter "until=24h"
          sudo docker image prune     -f --filter "until=24h"
